spring:
  jpa:
    hibernate:
      ddl-auto: none # 테스트 시 테이블 자동 생성 및 삭제
  datasource:
    url: jdbc:mysql://localhost:3306/cou_commerce
    username: root
    password: dsa991006!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 'iHExnZMqMwm/GbyUTqkRsCZpdcpup1sSI/R2CYVi4qc='
  refresh-token-expire-time: 360000
  access-token-expire-time: 3600000

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
