spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # CI에서 테이블 자동 생성 및 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 Dialect 명시
  datasource:
    url: jdbc:mysql://localhost:3306/cou_commerce # CI 서비스의 DB 이름
    username: root # CI 서비스의 사용자 이름
    password: root # CI 서비스의 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 'iHExnZMqMwm/GbyUTqkRsCZpdcpup1sSI/R2CYVi4qc='
  refresh-token-expire-time: 360000
  access-token-expire-time: 3600000

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
