spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cou_commerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dsa991006!
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: 'iHExnZMqMwm/GbyUTqkRsCZpdcpup1sSI/R2CYVi4qc='
  refresh-token-expire-time: 360000
  access-token-expire-time: 3600000
